### ISSUE TITLE
Research GitHub Actions by setting up a plugin project

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#110]
Create file: `.github/workflows/maven.yml`

Fill with configuration:
```YML
name: Java CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean compile package -P release-neodymium
```
