### ISSUE TITLE
NPE while parsing malformed YAML localization file

### ISSUE THREAD

**Issue by marcuskaufmann** [Xceptance/neodymium-library#44]
An NPE occurs if the localization file is malformed.

```yaml
en_US:
    empty:
    nonEmpty: "foobar"
```
